### ISSUE TITLE
Does hpl-gpu with cuda backend works on a pure cpu node?

### ISSUE THREAD

**Issue by yqin** [davidrohr/hpl-gpu#3]
I thought it should, at least that's the impression from reading the wiki. But in reality I got this,

CUDA Error 30: unknown error
caldgemm_cuda.cu:154
Getting Device Count
Error initializing CALDGEMM, abborting run

The dgemm_bench along runs on both cpu and gpu, and hybrid of both. The hpl-gpu build runs on cpu+gpu hybrid. But I was trying to test a cluster with some pure cpu nodes and some hybrid nodes and found that the cpu one does not run. Did I do something wrong? Or if there's special tuning that I need to do like dgemm_bench?

**Comment by yqin** [comment]
I think the issue is that hpl-gpu does not accept the command line option "-O" to adjust the backend dynamically. So you will have to build a separate version of hpl-gpu using the cpu backend, then run the cpu version on cpu nodes and the gpu version on gpu nodes.

**Comment by davidrohr** [comment]
MIght be, or you can hack the code to load different backends on different nodes. This running scenario was foreseen, but never fully tested.

**Comment by alansill** [comment]
Refreshing this issue to ask about current best practices for running on a heterogeneous (some pure CPU nodes + some nodes with GPUs) setup. Can you describe further the "hack the code to load different backends on different nodes" approach you mentioned in the comment of Jan. 6?

**Comment by davidrohr** [comment]
Not sure if it will start if the CUDA backend is compiled in and you try to run on a pure CPU node. Might depend on the availability of CUDA kernel module / drivers / runtime on the node. Would need to be tested.

What I meant is: You can compile twice, with `INCLDUE_CUDA` enabled and disabled in `config_options.mak`. Then, you distribute the one with enabled to the GPU nodes, and the one with disabled to the CPU nodes. Then you use mpi to start everything, but you have to start different binaries depending on the node type. Finally, there is a command line option to select the backend, don't remember which one. So obviously you must make sure that each node gets the correct command line option. The easiest hack is probably not to use a command line option at all but hack the code and include that option in the binary.
